// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaZM_C08tTyhdcU2PdMQ1NT8E8tKwL78',
    appId: '1:556540946179:web:3a6727d356cd2753e6ab36',
    messagingSenderId: '556540946179',
    projectId: 'newsapp-9b6d5',
    authDomain: 'newsapp-9b6d5.firebaseapp.com',
    storageBucket: 'newsapp-9b6d5.firebasestorage.app',
    measurementId: 'G-P1Z1Y0JZ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT8logI4qvCwbgZuGCQ11ncbLBKEf1-r4',
    appId: '1:556540946179:android:d2d85ba9c01c0494e6ab36',
    messagingSenderId: '556540946179',
    projectId: 'newsapp-9b6d5',
    storageBucket: 'newsapp-9b6d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-wcFHISJgUwP4dUz0MkjIQ5c7oT1C0I',
    appId: '1:556540946179:ios:4dd878bae49c688ee6ab36',
    messagingSenderId: '556540946179',
    projectId: 'newsapp-9b6d5',
    storageBucket: 'newsapp-9b6d5.firebasestorage.app',
    iosBundleId: 'com.example.newsSwipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-wcFHISJgUwP4dUz0MkjIQ5c7oT1C0I',
    appId: '1:556540946179:ios:4dd878bae49c688ee6ab36',
    messagingSenderId: '556540946179',
    projectId: 'newsapp-9b6d5',
    storageBucket: 'newsapp-9b6d5.firebasestorage.app',
    iosBundleId: 'com.example.newsSwipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfaZM_C08tTyhdcU2PdMQ1NT8E8tKwL78',
    appId: '1:556540946179:web:c1229221c6e14b18e6ab36',
    messagingSenderId: '556540946179',
    projectId: 'newsapp-9b6d5',
    authDomain: 'newsapp-9b6d5.firebaseapp.com',
    storageBucket: 'newsapp-9b6d5.firebasestorage.app',
    measurementId: 'G-ML46MSDVQL',
  );
}
